fix: first code group item is not open by default
grammyjs/docs-bot pull request #16
Opened 2023-06-22 15:29 UTC by dcdunkan

2023-06-22 15:31 UTC, KnorpelSenf commented
Perhaps the site will be fixed, we should wait

2023-06-25 14:40 UTC, dcdunkan commented
> Perhaps the site will be fixed, we should wait

Any updates?

2023-06-25 20:56 UTC, KnorpelSenf commented
None that I am aware of

2023-06-27 19:09 UTC, CikiMomogi requested changes

2023-06-27 19:09 UTC, CikiMomogi commented on iv-rules.txt
> +  @if ( $details[@aria-selected="true"] ) {
```suggestion
  @if ( $details//button[@ariaexpanded="true"] ) {
```

2023-06-28 08:39 UTC, KnorpelSenf commented
@roj1512 could you chip and let us know if this should be merged or if the website will be fixed instead?

2023-06-29 00:12 UTC, CikiMomogi approved these changes

2023-06-29 17:12 UTC, roj1512 approved these changes

2023-06-29 17:15 UTC, merged